name: frame_app_flutter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  intl: ^0.17.0
  dio: ^4.0.6
  equatable: ^2.0.3
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  package_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
